---
site_name: Ben's Dungeons and Dragons Sessions

site_url: https://0x08.github.io/dnd

docs_dir: dnd/

theme:
  name: material
  logo: assets/logo.png
  features:
    - navigation.prune
    - navigation.tabs
    - navigation.instant
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.magiclink
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - pymdownx.arithmatex: # Add the 'pymdownx.' prefix
      generic: true

extra_javascript:
  - https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      cache_safe: true
      htmlmin_opts:
        remove_comments: true
